### ISSUE TITLE
Failed to find component class for 'rasa_composite_entities.CompositeEntityExtractor' on $ rasa train

### ISSUE THREAD

**Issue by MaxGdr** [BeWe11/rasa_composite_entities#11]
Hello, i did pip install rasa_composite_entitites, and next tried with the latest rasa version to train with this config : 
```
language: "fr"

pipeline:
    - name: "WhitespaceTokenizer"
    - name: "RegexFeaturizer"
    - name: "CRFEntityExtractor"
    - name: "EntitySynonymMapper"
    - name: "CountVectorsFeaturizer"
    - name: "CountVectorsFeaturizer"
      analyzer: "char_wb"
      min_ngram: 1
      max_ngram: 4
    - name: "EmbeddingIntentClassifier"
      batch_strategy: "sequence"
    - BILOU_flag: true
      name: "CRFEntityExtractor"
      features:
          - [low, title, upper]
          - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
          - [low, title, upper]
```
Result : 
![image](https://user-images.githubusercontent.com/51989635/66047939-f433d180-e528-11e9-8425-9b50ab465f5c.png)

Do you have any idea ? 

To resume :
- pip install rasa
- pip install rasa_composite_entities
- add to config this : - name: "rasa_composite_entities.CompositeEntityExtractor")
- (shell cmd) rasa train
- error (see screenshot)
